# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10.8.1 # Need to specify version as we don't do a checkout here

      # Download release artifacts
      - name: release-downloader
        uses: robinraju/release-downloader@v1.12
        with:
          releaseId: ${{ github.event.release.id }}
          fileName: "*.tgz"

      - run: |
          # Find *.tgz file in the current directory
          file=$(ls *.tgz)
          # Publish this file to npm
          echo "Publishing $file to npm..."

          pnpm publish "$file" --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
